name: paradox
author: Seth Ladd <sethladd@gmail.com>
version: 0.0.1
description: HttpRequests that work even when offline.
homepage: https://github.com/sethladd/paradox.dart
dependencies:
  lawndart: any
  uuid: any
  cipher: '0.4.0'
dev_dependencies:
  browser: any
  http_server: any